### ISSUE TITLE
NameError: name 'dry' is not defined

### ISSUE THREAD

**Issue by Feathered-Serpent** [i30817/libretrofuzz#42]
Heya, it's me again...

added some games and wanted to call libretrofuzz again. I updated to the current version of libretrofuzz and run it. But the following stacktrace greeted me.
[libretrofuzz error.txt](https://github.com/i30817/libretrofuzz/files/13326472/libretrofuzz.error.txt)

Something wrong with my names again?

**Comment by i30817** [comment]
Something wrong with me! I put in a typo in a minor change. I suspect it was autocorrupt on the android GitHub application because I previously used that name on the comment.

I'll fix it right away.

**Comment by i30817** [comment]
Sorry for the wait. Haven't been visiting GitHub for reading fanfiction for a while. Fixed.

**Comment by Feathered-Serpent** [comment]
Works again, thanks!
